spring:
  data:
    elasticsearch:      client:        reactive:          endpoints:          - http://localhost:9200/
          use-ssl: true
          socket-timeout: 20s      repositories:        enabled: true